export default function Display(){

    return (
        <div id="display">
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam dui ligula, auctor sit amet consequat id, aliquam sit amet enim. Aenean efficitur nunc lacus, a volutpat sem suscipit at. Integer sit amet molestie sapien. Etiam elementum iaculis mi, eget posuere nunc finibus sed. Proin tempor varius diam, et hendrerit elit posuere nec. Duis ac turpis efficitur, pharetra urna et, rhoncus nisi. Vivamus aliquet luctus enim sed pharetra. Mauris posuere turpis sed nulla mollis, vitae ultricies neque varius. Nunc a neque felis. Sed facilisis mauris at consectetur elementum. Sed vestibulum augue id fringilla lacinia. Cras at lorem nibh. Suspendisse nec dapibus nibh. Pellentesque et luctus nibh, ut laoreet nisl. Sed luctus justo est, at commodo dui sodales eget.

Cras pharetra, dui at convallis vehicula, neque enim sollicitudin urna, eu lacinia nulla felis non nibh. Curabitur eget sem vel arcu pulvinar varius. Etiam ac enim quis elit sollicitudin consequat. Duis tempus augue neque, ac dapibus libero faucibus ac. Morbi imperdiet sit amet nisi vitae tincidunt. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam rhoncus id nisl vitae faucibus. Maecenas nunc est, volutpat in tempor a, luctus ut magna. Vestibulum sed nisi nisl.

Sed iaculis neque sem, rutrum condimentum velit tempus quis. Pellentesque hendrerit, lacus sit amet finibus euismod, enim sem maximus est, eu hendrerit arcu sem id sapien. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris luctus nulla nec risus tempus, et sodales turpis volutpat. Duis gravida pharetra odio sed euismod. Pellentesque elementum ornare fringilla. Ut sed tristique ante, eget vehicula metus. Etiam nec porttitor urna. Nulla ultrices odio non enim varius interdum. Maecenas congue dui nec est cursus, id tristique eros eleifend. Maecenas dictum ultrices sem, at ultrices augue iaculis nec. Proin faucibus sem eget ante posuere, non iaculis urna scelerisque. Cras sed augue ipsum. Curabitur sagittis justo vel aliquet auctor.

Integer ac metus fermentum, porttitor eros sit amet, tempor lorem. Phasellus non consequat erat. Suspendisse pulvinar ex quis nulla fermentum, a laoreet nibh volutpat. Curabitur sed malesuada risus, quis faucibus dolor. Fusce luctus, risus a convallis semper, lorem libero tempor tortor, nec fringilla justo odio non nunc. Suspendisse semper fringilla lectus, ut feugiat justo dictum vitae. Suspendisse commodo mollis felis ut sollicitudin. Aenean eu leo nisl. Donec ut nulla commodo, pulvinar nisl eu, aliquet orci.</p>
        </div>
    )
}